name: Node.js CI
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    strategy:
       matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i -g vue-cli
    - run: npm install
    - run: echo ${{ secrets.ENV_FILE }} > .env
    - run: cat .env
    - run: npm run build
      env:
        VUE_APP_API_URL: "${{ secrets.VUE_APP_API_URL }}"
        VUE_APP_I18N_LOCALE: "${{ secrets.VUE_APP_I18N_LOCALE }}"
        VUE_APP_I18N_FALLBACK_LOCALE: "${{ secrets.VUE_APP_I18N_FALLBACK_LOCALE }}"
    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
        ARGS: "-rltgoDzvO"
        SOURCE: "static/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
